# Generated by Django 5.2.7 on 2026-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveylink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveylink',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
